# This is the workflow for create-standup-discussions

name: Create Daily Standup Discussions

on:
  schedule:
    - cron:  '29 22 * * MON-FRI' # Runs M-F at 2:29pm

jobs:
  create_discussions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: MLH-Fellowship/create-standup-discussions@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ORGANIZATION_TOKEN }}
        with:
          organization: "CSE-110-Test-Team"
          team_slugs: "me"
